name = "darkscreen-email-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "INBOX"
id = "b3b4e8d0355546e18a17bfc18e8defdb"

[vars]
SENDER_NAME = "Minjae"
SENDER_EMAIL = "minjae@darkscreens.xyz"
